[AngryPeds]

# Toggle key
ToggleKey=F3

# Radius in meters
AggroRadius=1000.0

# Give weapons (true/false)
GiveWeapons=true

# Infinite ammo (true/false)
InfiniteAmmo=true

# Infinite clip (true/false)
InfiniteClip=true

# Weapons: [random] or [pistol] or [pistol,knife ect...]
Weapons=[pistol]

# Interval in ms
IntervalMS=500
